# Generated by Django 2.2.5 on 2019-09-30 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contributor', models.CharField(db_index=True, max_length=280)),
            ],
            options={
                'verbose_name': 'List of the contributors',
                'ordering': ['contributor'],
                'get_latest_by': 'contributor',
            },
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('iswc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=280)),
            ],
            options={
                'verbose_name': 'List of the single views',
                'ordering': ['title'],
                'get_latest_by': 'title',
            },
        ),
        migrations.CreateModel(
            name='SingleViewContributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Contributor')),
                ('iswc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Single')),
            ],
            options={
                'verbose_name': 'Link table btween contributors and singles',
                'ordering': ['iswc', 'contributor_id'],
                'get_latest_by': 'iswc',
                'index_together': {('iswc', 'contributor_id')},
            },
        ),
    ]
